// Powered by OnSpace.AI
export type Language = 'en' | 'ur' | 'ar';
export type Direction = 'ltr' | 'rtl';

export const LanguageMeta: Record<Language, { label: string; nativeLabel: string; direction: Direction; font: string }> = {
  en: { label: 'English', nativeLabel: 'English', direction: 'ltr', font: 'System' },
  ur: { label: 'Urdu', nativeLabel: 'اردو', direction: 'rtl', font: 'System' },
  ar: { label: 'Arabic', nativeLabel: 'العربية', direction: 'rtl', font: 'System' },
};

export const Strings: Record<Language, Record<string, string>> = {
  en: {
    appName: 'ThumbCraft Pro',
    appTagline: 'Professional Thumbnail Generator',
    home: 'Home',
    generator: 'Generator',
    templates: 'Templates',
    settings: 'Settings',
    admin: 'Admin',
    createThumbnail: 'Create Thumbnail',
    myProjects: 'My Projects',
    recentProjects: 'Recent Projects',
    templates_: 'Templates',
    chooseTemplate: 'Choose Template',
    customize: 'Customize',
    export: 'Export',
    share: 'Share',
    save: 'Save',
    saved: 'Saved',
    autoSaved: 'Auto Saved',
    title: 'Title Text',
    subtitle: 'Subtitle Text',
    background: 'Background',
    textColor: 'Text Color',
    fontSize: 'Font Size',
    fontFamily: 'Font Family',
    bold: 'Bold',
    italic: 'Italic',
    align: 'Alignment',
    opacity: 'Opacity',
    rotation: 'Rotation',
    scale: 'Scale',
    addShape: 'Add Shape',
    addText: 'Add Text',
    addImage: 'Add Image',
    addGradient: 'Add Gradient',
    layers: 'Layers',
    canvas: 'Canvas',
    size: 'Size',
    undo: 'Undo',
    redo: 'Redo',
    delete: 'Delete',
    duplicate: 'Duplicate',
    adminPanel: 'Admin Panel',
    adminLogin: 'Admin Login',
    enterPassword: 'Enter Password',
    password: 'Password',
    login: 'Login',
    logout: 'Logout',
    wrongPassword: 'Incorrect password',
    adminWelcome: 'Welcome, Administrator',
    themeSettings: 'Theme Settings',
    languageSettings: 'Language Settings',
    launcherSettings: 'Launcher Settings',
    canvasSettings: 'Canvas Settings',
    exportSettings: 'Export Settings',
    appSettings: 'App Settings',
    colorScheme: 'Color Scheme',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    language: 'Language',
    direction: 'Text Direction',
    launcher: 'Launcher Theme',
    selectLauncher: 'Select Launcher',
    canvasWidth: 'Canvas Width',
    canvasHeight: 'Canvas Height',
    exportFormat: 'Export Format',
    exportQuality: 'Export Quality',
    resolution: 'Resolution',
    watermark: 'Watermark',
    watermarkText: 'Watermark Text',
    appLogo: 'App Logo',
    primaryColor: 'Primary Color',
    accentColor: 'Accent Color',
    reset: 'Reset to Defaults',
    saveSettings: 'Save Settings',
    newProject: 'New Project',
    untitled: 'Untitled',
    projects: 'Projects',
    noProjects: 'No projects yet',
    startCreating: 'Start creating your first thumbnail',
    youtube: 'YouTube (1280x720)',
    instagram: 'Instagram (1080x1080)',
    twitter: 'Twitter (1200x675)',
    facebook: 'Facebook (1200x630)',
    linkedin: 'LinkedIn (1200x627)',
    custom: 'Custom Size',
    shapes: 'Shapes',
    gradients: 'Gradients',
    effects: 'Effects',
    filters: 'Filters',
    glow: 'Glow',
    shadow: 'Shadow',
    blur: 'Blur',
    brightness: 'Brightness',
    contrast: 'Contrast',
    saturation: 'Saturation',
    preview: 'Preview',
    close: 'Close',
    ok: 'OK',
    cancel: 'Cancel',
    confirm: 'Confirm',
  },
  ur: {
    appName: 'تھمب کرافٹ پرو',
    appTagline: 'پیشہ ور تھمب نیل جنریٹر',
    home: 'ہوم',
    generator: 'جنریٹر',
    templates: 'ٹیمپلیٹس',
    settings: 'ترتیبات',
    admin: 'ایڈمن',
    createThumbnail: 'تھمب نیل بنائیں',
    myProjects: 'میرے پروجیکٹس',
    recentProjects: 'حالیہ پروجیکٹس',
    templates_: 'ٹیمپلیٹس',
    chooseTemplate: 'ٹیمپلیٹ چنیں',
    customize: 'کسٹمائز',
    export: 'برآمد',
    share: 'شیئر',
    save: 'محفوظ',
    saved: 'محفوظ ہو گیا',
    autoSaved: 'خودبخود محفوظ',
    title: 'عنوان',
    subtitle: 'ذیلی عنوان',
    background: 'پس منظر',
    textColor: 'متن کا رنگ',
    fontSize: 'فونٹ سائز',
    fontFamily: 'فونٹ خاندان',
    bold: 'بولڈ',
    italic: 'ترچھا',
    align: 'سیدھ',
    opacity: 'شفافیت',
    rotation: 'گردش',
    scale: 'پیمانہ',
    addShape: 'شکل شامل کریں',
    addText: 'متن شامل کریں',
    addImage: 'تصویر شامل کریں',
    addGradient: 'گریڈیئنٹ شامل کریں',
    layers: 'تہیں',
    canvas: 'کینوس',
    size: 'سائز',
    undo: 'واپس',
    redo: 'آگے',
    delete: 'حذف',
    duplicate: 'نقل',
    adminPanel: 'ایڈمن پینل',
    adminLogin: 'ایڈمن لاگ ان',
    enterPassword: 'پاس ورڈ درج کریں',
    password: 'پاس ورڈ',
    login: 'لاگ ان',
    logout: 'لاگ آؤٹ',
    wrongPassword: 'غلط پاس ورڈ',
    adminWelcome: 'خوش آمدید، ایڈمنسٹریٹر',
    themeSettings: 'تھیم ترتیبات',
    languageSettings: 'زبان کی ترتیبات',
    launcherSettings: 'لانچر ترتیبات',
    canvasSettings: 'کینوس ترتیبات',
    exportSettings: 'برآمد ترتیبات',
    appSettings: 'ایپ ترتیبات',
    colorScheme: 'رنگ اسکیم',
    darkMode: 'ڈارک موڈ',
    lightMode: 'لائٹ موڈ',
    language: 'زبان',
    direction: 'متن کی سمت',
    launcher: 'لانچر تھیم',
    selectLauncher: 'لانچر چنیں',
    canvasWidth: 'کینوس چوڑائی',
    canvasHeight: 'کینوس اونچائی',
    exportFormat: 'برآمد فارمیٹ',
    exportQuality: 'برآمد معیار',
    resolution: 'ریزولیوشن',
    watermark: 'واٹر مارک',
    watermarkText: 'واٹر مارک متن',
    appLogo: 'ایپ لوگو',
    primaryColor: 'بنیادی رنگ',
    accentColor: 'ایکسینٹ رنگ',
    reset: 'ڈیفالٹ پر ری سیٹ',
    saveSettings: 'ترتیبات محفوظ کریں',
    newProject: 'نیا پروجیکٹ',
    untitled: 'بے عنوان',
    projects: 'پروجیکٹس',
    noProjects: 'ابھی کوئی پروجیکٹ نہیں',
    startCreating: 'اپنا پہلا تھمب نیل بنانا شروع کریں',
    youtube: 'یوٹیوب (1280x720)',
    instagram: 'انسٹاگرام (1080x1080)',
    twitter: 'ٹوئٹر (1200x675)',
    facebook: 'فیس بک (1200x630)',
    linkedin: 'لنکڈ ان (1200x627)',
    custom: 'کسٹم سائز',
    shapes: 'شکلیں',
    gradients: 'گریڈیئنٹس',
    effects: 'اثرات',
    filters: 'فلٹرز',
    glow: 'چمک',
    shadow: 'سایہ',
    blur: 'دھندلاپن',
    brightness: 'روشنی',
    contrast: 'کنٹراسٹ',
    saturation: 'سیچوریشن',
    preview: 'پیش نظارہ',
    close: 'بند',
    ok: 'ٹھیک',
    cancel: 'منسوخ',
    confirm: 'تصدیق',
  },
  ar: {
    appName: 'ثمب كرافت برو',
    appTagline: 'منشئ الصور المصغرة الاحترافي',
    home: 'الرئيسية',
    generator: 'المنشئ',
    templates: 'القوالب',
    settings: 'الإعدادات',
    admin: 'المدير',
    createThumbnail: 'إنشاء صورة مصغرة',
    myProjects: 'مشاريعي',
    recentProjects: 'المشاريع الأخيرة',
    templates_: 'القوالب',
    chooseTemplate: 'اختر قالبًا',
    customize: 'تخصيص',
    export: 'تصدير',
    share: 'مشاركة',
    save: 'حفظ',
    saved: 'تم الحفظ',
    autoSaved: 'حفظ تلقائي',
    title: 'نص العنوان',
    subtitle: 'نص العنوان الفرعي',
    background: 'الخلفية',
    textColor: 'لون النص',
    fontSize: 'حجم الخط',
    fontFamily: 'عائلة الخط',
    bold: 'عريض',
    italic: 'مائل',
    align: 'المحاذاة',
    opacity: 'الشفافية',
    rotation: 'التدوير',
    scale: 'الحجم',
    addShape: 'إضافة شكل',
    addText: 'إضافة نص',
    addImage: 'إضافة صورة',
    addGradient: 'إضافة تدرج',
    layers: 'الطبقات',
    canvas: 'اللوحة',
    size: 'الحجم',
    undo: 'تراجع',
    redo: 'إعادة',
    delete: 'حذف',
    duplicate: 'نسخ',
    adminPanel: 'لوحة الإدارة',
    adminLogin: 'تسجيل دخول المدير',
    enterPassword: 'أدخل كلمة المرور',
    password: 'كلمة المرور',
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    wrongPassword: 'كلمة المرور غير صحيحة',
    adminWelcome: 'مرحبًا، المدير',
    themeSettings: 'إعدادات السمة',
    languageSettings: 'إعدادات اللغة',
    launcherSettings: 'إعدادات المشغل',
    canvasSettings: 'إعدادات اللوحة',
    exportSettings: 'إعدادات التصدير',
    appSettings: 'إعدادات التطبيق',
    colorScheme: 'نظام الألوان',
    darkMode: 'الوضع الداكن',
    lightMode: 'الوضع الفاتح',
    language: 'اللغة',
    direction: 'اتجاه النص',
    launcher: 'سمة المشغل',
    selectLauncher: 'اختر مشغلًا',
    canvasWidth: 'عرض اللوحة',
    canvasHeight: 'ارتفاع اللوحة',
    exportFormat: 'تنسيق التصدير',
    exportQuality: 'جودة التصدير',
    resolution: 'الدقة',
    watermark: 'العلامة المائية',
    watermarkText: 'نص العلامة المائية',
    appLogo: 'شعار التطبيق',
    primaryColor: 'اللون الأساسي',
    accentColor: 'لون التمييز',
    reset: 'إعادة التعيين',
    saveSettings: 'حفظ الإعدادات',
    newProject: 'مشروع جديد',
    untitled: 'بدون عنوان',
    projects: 'المشاريع',
    noProjects: 'لا توجد مشاريع بعد',
    startCreating: 'ابدأ إنشاء أول صورة مصغرة لك',
    youtube: 'يوتيوب (1280x720)',
    instagram: 'انستغرام (1080x1080)',
    twitter: 'تويتر (1200x675)',
    facebook: 'فيسبوك (1200x630)',
    linkedin: 'لينكد ان (1200x627)',
    custom: 'حجم مخصص',
    shapes: 'الأشكال',
    gradients: 'التدرجات',
    effects: 'التأثيرات',
    filters: 'الفلاتر',
    glow: 'توهج',
    shadow: 'ظل',
    blur: 'ضبابية',
    brightness: 'السطوع',
    contrast: 'التباين',
    saturation: 'التشبع',
    preview: 'معاينة',
    close: 'إغلاق',
    ok: 'حسنًا',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
  },
};
